name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"

  trigger_changes:
    runs-on: ubuntu-latest
    needs: greet
    if: github.ref == 'refs/heads/deployment'
    steps:
      - name: Trigger Changes
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKENN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/UttU28/Portfolio/dispatches \
            -d '{"event_type": "trigger-changes"}'

